framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'  # par exemple, une file d'attente doctrine ou amqp
            sync: 'sync://'

        routing:
            # Route tous les messages de SendEmailMessage via le transport "sync"
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
